server:
  port: 8888

spring:
  #profiles:
  #  active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adrianodts/microservice-repo.git          search-paths: /fornecedor
        #native:
        #  search-locations: c:/microservice-repo